### ISSUE TITLE
MacOS `compileKotlinIosArm64` Fails

### ISSUE THREAD

**Issue by gmitch215** [korlibs/korge#2269]
Trying to build a Xcode project using the app. Using a Macbook Air on an Intel chip.

```
> Task :compileKotlinIosArm64 FAILED
e: KLIB resolver: Could not find "com.soywiz.korge:korlibs-serialization-yaml" in [/Users/gamer/.../project, /Users/gamer/.konan/klib, /Users/gamer/.konan/kotlin-native-prebuilt-macos-x86_64-2.0.0/klib/common, /Users/gamer/.konan/kotlin-native-prebuilt-macos-x86_64-2.0.0/klib/platform/ios_arm64]
```

Transformed libraries look like this:
<details>
    <summary>Click to View</summary>

![image](https://github.com/user-attachments/assets/2f803c94-f860-4ae1-83e1-af46d17523a9)
</details>

Using Korge v6.0.0-alpha9.

**Reproduce**: Build a simple app using the specified version, then use `targetIos` and attempt to build the project.

**Comment by soywiz** [comment]
serialization-yaml is not referenced anymore on master, o I guess this will be fixed in the next version. Let's retry after the next release

**Comment by gmitch215** [comment]
@soywiz When will that be?

**Comment by soywiz** [comment]
Right now I have been working on korlibs longstanding issues related to sound, locking and threading. I expect to finish it soon, likely before the end of the week. Then I will make a release, will check iOS and Android that have not been tested in detail in alpha versions, and will update all the kprojects from the store. ETA something between the end of the week and next week, but can't promise on that since it depends on issues I might find.

**Comment by soywiz** [comment]
Fixed in korlibs-6.0.0-beta1

**Comment by gmitch215** [comment]
@soywiz Did you make a release on this repository?

```
* What went wrong:
Plugin [id: 'com.soywiz.korge', version: '6.0.0-beta1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (No included builds contain this plugin)
- Plugin Repositories (could not resolve plugin artifact 'com.soywiz.korge:com.soywiz.korge.gradle.plugin:6.0.0-beta1')
  Searched in the following repositories:
    MavenLocal(file:~/.m2/repository/)
    MavenRepo
    Google
    Gradle Central Plugin Repository
```

**Comment by soywiz** [comment]
Yes, I triggered a release, but it seems that it didn't completed successfully on the first try. Central is not working properly for me.

I have reopened the issue. korlibs-all 6.0.0-beta1 is already on central.

**Comment by gmitch215** [comment]
@soywiz When will the issue for central fix?

**Comment by gmitch215** [comment]
Also, it still doesn't work. I cloned the repository, ran `./gradlew publishToMavenLocal`, and used the local version, but I still et this:

```
> Task :compileKotlinIosArm64 FAILED
e: KLIB resolver: Could not find "com.soywiz.korge:korlibs-serialization-yaml" in [~/gmitch215/../project, ~/.konan/klib, ~/.konan/kotlin-native-prebuilt-macos-x86_64-2.0.0/klib/common, ~/.konan/kotlin-native-prebuilt-macos-x86_64-2.0.0/klib/platform/ios_arm64

```

**Comment by soywiz** [comment]
> Also, it still doesn't work. I cloned the repository, ran `./gradlew publishToMavenLocal`, and used the local version, but I still et this:
> 
> ```
> > Task :compileKotlinIosArm64 FAILED
> e: KLIB resolver: Could not find "com.soywiz.korge:korlibs-serialization-yaml" in [~/gmitch215/../project, ~/.konan/klib, ~/.konan/kotlin-native-prebuilt-macos-x86_64-2.0.0/klib/common, ~/.konan/kotlin-native-prebuilt-macos-x86_64-2.0.0/klib/platform/ios_arm64
> ```

How can I reproduce this?

**Comment by gmitch215** [comment]
@soywiz
A simple KorGE project running `targetIos` on any Macbook should work. If not, I can send some project files.

**Comment by soywiz** [comment]
I have been a few days trying to properly publish 6.0.0-beta1, but it seems that sonatype/central is unstable. So I'm doing now something I was been deferring: I'm going to split the libraries in smaller repositiories and publish them independently. I'll come back when done.

**Comment by gmitch215** [comment]
@soywiz Any updates? I see that it's now properly on central.

**Comment by gmitch215** [comment]
Seems not to persist anymore.
